Industry.create(name: 'Consumer Discretionary')
Industry.create(name: 'Consumer Staples')
Industry.create(name: 'Energy')
Industry.create(name: 'Financials')
Industry.create(name: 'Health Care')
Industry.create(name: 'Industrials')
Industry.create(name: 'Information Technology')
Industry.create(name: 'Materials')
Industry.create(name: 'Real Estate')
Industry.create(name: 'Telecommunication Services')
Industry.create(name: 'Utilities')